# Generated by Django 4.2.26 on 2026-03-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0098_data_local_storage_backing_cs"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabeledInterval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("frame", models.PositiveIntegerField()),
                ("group", models.PositiveIntegerField(null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("auto", "AUTO"),
                            ("semi-auto", "SEMI_AUTO"),
                            ("manual", "MANUAL"),
                            ("file", "FILE"),
                            ("consensus", "CONSENSUS"),
                        ],
                        default="manual",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("end_frame", models.PositiveIntegerField()),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="engine.job")),
                ("label", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="engine.label")),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="LabeledIntervalAttributeVal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=4096)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="engine.job")),
                ("spec", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="engine.attributespec")),
                (
                    "interval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="attributes",
                        related_query_name="attribute",
                        to="engine.labeledinterval",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="labeledinterval",
            constraint=models.CheckConstraint(
                check=models.Q(("end_frame__gte", models.F("frame"))),
                name="labeledinterval_frame_lte_end_frame",
            ),
        ),
    ]

