# Generated by Django 4.2.26 on 2026-03-21 00:00

import cvat.apps.engine.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0098_data_local_storage_backing_cs"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobNarration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        max_length=1024,
                        storage=cvat.apps.engine.models.MyFileSystemStorage(),
                        upload_to=cvat.apps.engine.models.narration_upload_path_handler,
                    ),
                ),
                ("sample_rate", models.PositiveIntegerField(blank=True, null=True)),
                ("video_time_offset", models.FloatField(default=0)),
                ("start_wallclock", models.DateTimeField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narrations",
                        related_query_name="narration",
                        to="engine.job",
                    ),
                ),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="auth.user")),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]

