# Generated by Django 4.2.26 on 2026-03-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0101_job_classification"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobTranscript",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(
                    choices=[
                        ("pending", "Pending"),
                        ("processing", "Processing"),
                        ("completed", "Completed"),
                        ("failed", "Failed"),
                    ],
                    default="pending",
                    max_length=16,
                )),
                ("raw_transcript", models.TextField(blank=True, default="")),
                ("corrected_transcript", models.TextField(blank=True, default="")),
                ("word_timestamps", models.JSONField(blank=True, default=list)),
                ("error_message", models.TextField(blank=True, default="")),
                ("model_info", models.JSONField(blank=True, default=dict)),
                (
                    "narration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript",
                        related_query_name="transcript",
                        to="engine.jobnarration",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
