# Generated by Django 4.2.26 on 2026-03-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0102_job_transcript"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurgeryModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("procedure_type", models.CharField(max_length=128)),
                ("model_type", models.CharField(
                    choices=[
                        ("phase_classifier", "Phase Classifier"),
                        ("task_classifier", "Task Classifier"),
                        ("anatomy_segmenter", "Anatomy Segmenter"),
                    ],
                    max_length=32,
                )),
                ("endpoint_url", models.URLField(max_length=512)),
                ("is_active", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="surgerymodel",
            constraint=models.UniqueConstraint(
                fields=["name", "procedure_type"],
                name="surgery_model_unique",
            ),
        ),
    ]
