# Generated by Django 4.2.26 on 2026-03-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0103_surgery_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="end_frame",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("frame", "Frame"),
                    ("interval", "Interval"),
                    ("narration", "Narration"),
                ],
                default="frame",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="narration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                related_query_name="issue",
                to="engine.jobnarration",
            ),
        ),
    ]
