# Generated by Django 4.2.26 on 2026-03-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0104_issue_interval_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="OntologyVersion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("schema", models.JSONField()),
                ("description", models.TextField(blank=True, default="")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ontology_versions",
                        related_query_name="ontology_version",
                        to="engine.project",
                    ),
                ),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="auth.user")),
            ],
            options={
                "default_permissions": (),
                "ordering": ["-version"],
            },
        ),
        migrations.AddConstraint(
            model_name="ontologyversion",
            constraint=models.UniqueConstraint(
                fields=["project", "version"],
                name="ontology_version_unique",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="pinned_ontology_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="engine.ontologyversion",
            ),
        ),
    ]
