# Generated by Django 4.2.26 on 2026-03-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0106_dataset_episode"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("surgeon", "Surgeon"),
                    ("engineer", "Engineer"),
                    ("researcher", "Researcher"),
                    ("reviewer", "Reviewer"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="expertise_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("resident", "Resident"),
                    ("fellow", "Fellow"),
                    ("attending", "Attending"),
                    ("expert", "Expert"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="specialty",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="profile",
            name="institution",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_complete",
            field=models.BooleanField(default=False),
        ),
    ]
